# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nb',
                'doc_host': 'https://haimianxing.github.io',
                'git_url': 'https://github.com/haimianxing/nb',
                'lib_path': 'nb'},
  'syms': { 'nb.core': { 'nb.core.HelloSayer': ('core.html#hellosayer', 'nb/core.py'),
                         'nb.core.HelloSayer.__init__': ('core.html#hellosayer.__init__', 'nb/core.py'),
                         'nb.core.HelloSayer.say': ('core.html#hellosayer.say', 'nb/core.py'),
                         'nb.core.foo': ('core.html#foo', 'nb/core.py'),
                         'nb.core.say_hello': ('core.html#say_hello', 'nb/core.py')}}}
